/****************************************************************************************************
Sample SQL files for the class 'Introduction to SQL and Postgres'
2025 Copyright: Marc Linster
Last updated Aug 22 2025


****************************************************************************************************/

-- dlh1.sql

/*

Section: Tables and Queries: Basics

*/

-- make sure you are connected to dlh1 database

SELECT current_database()

-- create a simple table

DROP TABLE IF EXISTS mycustomer;

CREATE TABLE mycustomer (
	id INTEGER,
	email TEXT,
	first_name TEXT,
	last_name TEXT,
	since DATE
);

/*

Section: Query Basics

*/


INSERT INTO mycustomer (id, email, first_name, last_name, since) 
	VALUES 
		(1,'marc@marclinster.com', 'Marc', 'Linster','1.1.2025'),
		(2,'jmu@gmail.lu','Jeff', 'Mueller','1.2.2025'),
		(3,'bini@hotmail.lu', 'Jean','Bintner','1.3.2025');


SELECT first_name FROM mycustomer;

SELECT first_name, last_name FROM mycustomer;

SELECT * FROM mycustomer WHERE first_name LIKE 'Je%';

SELECT * FROM mycustomer WHERE first_name LIKE 'je%';

SELECT * FROM mycustomer WHERE first_name ILIKE 'je%';

SELECT * FROM mycustomer WHERE first_name LIKE '_e%';

/*

Section: Operators

*/

SELECT * FROM mycustomer WHERE since 
	BETWEEN '2025-01-02' AND '2025-02-01';

SELECT
	first_name || ' ' || last_name AS customer_name
FROM
	mycustomer
WHERE
	first_name LIKE 'Je%';

-- use FORMAT instaed of string append ||

SELECT
	FORMAT ('%s %s', first_name, last_name) 
		AS customer_name
FROM
	mycustomer
WHERE
	first_name LIKE 'Je%';	

-- try the EXTRACT DOY function

SELECT 'It is the ' || EXTRACT (DOY FROM current_date) || 'th day of the year';

-- and

SELECT 'It is the ' || EXTRACT (DOY FROM current_date) || 'th day of the year' AS day_of_year;


-- simple calculations in the select clause

SELECT
	first_name || ' ' || last_name 
		AS customer_name,
	'Customer for ' || EXTRACT (DAY FROM NOW() - since) || ' ' || 'days' 
		AS how_long
FROM
	mycustomer;	

-- use FORMAT instaed of string append ||

SELECT
	FORMAT ('%s %s', first_name, last_name) 
		AS customer_name
FROM
	MYCUSTOMER
WHERE
	FIRST_NAME LIKE 'Je%';	

-- simple calculations in the select clause

SELECT
	FORMAT ('%s %s', first_name, last_name) 
		AS customer_name,
	'Customer for ' || EXTRACT (DAY FROM NOW() - since) || ' ' || 'days' 
		AS how_long
FROM
	MYCUSTOMER;


/*

Section: Primary Keys, Constraints and Relationships

*/

-- create the myproduct table

CREATE TABLE myproduct (
	product_nbr VARCHAR(10),
	name TEXT,
	price numeric
);	

-- add a primary key and a unique constraint
DROP TABLE IF EXISTS myproduct;

CREATE TABLE myproduct (
	nbr VARCHAR(10) PRIMARY KEY,
	name TEXT UNIQUE NOT NULL,
	price NUMERIC NOT NULL CHECK (price > 0) 
);

INSERT INTO myproduct (nbr, name, price) 
	VALUES 
		('ham_001','Hammer 200gr', 19.95),
		('ham_002', 'Hammer 1kg', 25.00),
		('chisel_004', 'Chisel stone', 39.95),
		('pli_019', 'Pliers red, adjustable', '13.50');

SELECT * FROM myproduct ORDER BY price ASC;

-- add table myorder to illustrate relations and foreign keys

DROP TABLE IF EXISTS myorder;

CREATE TABLE myorder (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	date DATE,
	product_nbr VARCHAR(10),
	qty INTEGER NOT NULL CHECK (qty > 0)
);

INSERT INTO myorder 
(date,product_nbr, qty) 
VALUES ('2.2.2025', 'chisel_004', 9);



-- nonsense order
INSERT INTO myorder 
(date,product_nbr, qty) 
VALUES ('2.2.2025', 'cheese_10', 9);


SELECT * FROM myorder;


SELECT * FROM myorder, myproduct
	WHERE myorder.product_id = myproduct.id;

-- add a foreign key constraint to make sure all orders refer to existing products

DROP TABLE IF EXISTS myorder;

CREATE TABLE myorder (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	date DATE,
	product_nbr VARCHAR(10) REFERENCES myproduct (nbr),
	qty INTEGER NOT NULL CHECK (qty > 0)
);
-- order for a chisel
INSERT INTO myorder (date,product_nbr, qty) 
	VALUES ('2.2.2025', 'chisel_004', 9);

-- nonsense order
INSERT INTO myorder 
(date,product_nbr, qty) 
VALUES ('2.2.2025', 'cheese_10', 9);


SELECT * FROM myorder, myproduct
WHERE myorder.product_nbr = myproduct.nbr;
	

-- Linking customers, orders and products
-- make sure that all orders refer to existing customers and products

ALTER TABLE myorder ADD COLUMN customer_id INTEGER REFERENCES mycustomer(id);

ALTER TABLE mycustomer ADD CONSTRAINT mycustomer_id_unq UNIQUE (id);

UPDATE myorder SET customer_id = 1 WHERE id = 1;

SELECT * FROM myorder;

SELECT * FROM myorder o, myproduct p, mycustomer c
	WHERE o.product_nbr = p.nbr
	AND o.customer_id = c.id;

-- excercise slide 64

INSERT INTO mycustomer (id, email, first_name, last_name, since) 
	VALUES 
		(4,'marc@marclinster.com', 'Marc', 'Linster','1.1.2025'),
		(5,'jmu@gmail.lu','Jeff', 'Mueller','1.2.2025'),
		(6,'bini@hotmail.lu', 'Jean','Bintner','1.3.2025');

INSERT INTO myproduct (nbr, name, price)
   VALUES
       ('ham_003','Hammer Large 500gr', 19.95),
       ('ham_004', 'Hammer Extra Large 1000gr', 25.00),
       ('chisel_005', 'Chisel wood', 12.87),
       ('pli_020', 'Pliers black, fixed', 3.50);	


SELECT o.id AS order_id, 
		o.date AS order_date, 
		c.first_name || ' ' || c.last_name AS customer_name,
		p.name AS product_name,
		p.price AS unit_price,
		o.qty AS order_qty,
		o.qty * p.price AS extended_price
	FROM myorder o,
		myproduct p, mycustomer c 
	WHERE o.product_nbr = p.nbr
		AND o.customer_id = c.id
	ORDER BY order_date ASC;
	
/*

Section: Database Joins

*/


SELECT * FROM myorder
	JOIN mycustomer
	ON myorders.customer_id = mycustomer.id;

SELECT 
	o.id AS order_id, 
	o.date AS order_date, 
	o.qty AS order_quantity, 
	c.first_name || ' ' || c.last_name AS customer_name
FROM myorder o
	JOIN mycustomer c
	ON o.customer_id = c.id;

-- customers even if they didn't order anything
SELECT * FROM mycustomer c
	LEFT OUTER JOIN myorder o
	ON c.id = o.customer_id;

-- customers who never ordered anything
SELECT * FROM mycustomer c
	LEFT OUTER JOIN myorder o
	ON c.id = o.customer_id
	WHERE o.id IS NULL;

-- customers with order details, or blank if they didn't order anything
SELECT * FROM mycustomer c
	LEFT JOIN myorder o ON c.id = o.customer_id
	LEFT JOIN myproduct p ON o.product_nbr = p.nbr;	
	
-- products that were never ordered

SELECT DISTINCT(p.*) FROM myproduct p
	LEFT JOIN myorder o ON o.product_nbr = p. nbr
	WHERE o.id IS NULL

/*

-- Section: Views

*/


CREATE OR REPLACE VIEW mycustomer_with_purchase_view AS 
	SELECT 
		c.id AS customer_id,
		FORMAT ('%s %s', c.first_name, c.last_name) AS customer_name,
		c.since AS customer_since,
		o.id AS order_number,
		o.date AS order_date,
		p.name AS product_name,
		p.price AS product_unit_price,
		p.price * o.qty AS extended_price
	FROM mycustomer c
		LEFT JOIN myorder o ON c.id = o.customer_id
		LEFT JOIN myproduct p ON o.product_nbr = p.nbr;	

SELECT * FROM mycustomer_with_purchase_view;

/****************************************************************************************************
                                              End of File
****************************************************************************************************/