/****************************************************************************************************
Sample SQL files for the class 'Introduction to SQL and Postgres'
2025 Copyright: Marc Linster
Last updated 2026-01-12


****************************************************************************************************/

-- dlh1.sql

/*

Section: Tables and Queries: Basics

*/

-- make sure you are connected to dlh1 database

SELECT current_database()

-- create a simple table

DROP TABLE IF EXISTS mycustomer;

CREATE TABLE mycustomer (
	id INTEGER PRIMARY KEY,
	email TEXT,
	first_name TEXT,
	last_name TEXT,
	since DATE
);

/*

Section: Query Basics

*/


INSERT INTO mycustomer (id, email, first_name, last_name, since) 
	VALUES 
		(1,'marc@marclinster.com', 'Marc', 'Linster','2025-01-01'),
		(2,'jmu@gmail.lu','Jeff', 'Mueller','2024-05-06'),
		(3,'bini@hotmail.lu', 'Jean','Bintner','2023-09-07');


SELECT first_name FROM mycustomer;

SELECT first_name, last_name FROM mycustomer;
SELECT * FROM mycustomer WHERE first_name LIKE 'Je%';
SELECT * FROM mycustomer WHERE first_name LIKE 'je%';
SELECT * FROM mycustomer WHERE first_name ILIKE 'je%';
SELECT * FROM mycustomer WHERE first_name LIKE '_e%';

UPDATE mycustomer SET first_name = 'Mark' WHERE id = 1;
SELECT * FROM mycustomer;
DELETE FROM mycustomer WHERE id = 1;
INSERT INTO mycustomer (id, email, first_name, last_name, since) 
	VALUES 
		(1,'marc@marclinster.com', 'Marc', 'Linster','2025-01-01');

SELECT * FROM mycustomer;
SELECT * FROM mycustomer ORDER BY last_name ASC;


/* Section: Operators in the WHERE clause */

SELECT * FROM mycustomer;
SELECT * FROM mycustomer WHERE id = 1;
SELECT * FROM mycustomer WHERE id = 1 OR id = 3;
SELECT * FROM mycustomer WHERE id IN (1,2);
SELECT email, last_name, first_name 
	FROM mycustomer 
	WHERE id IN (1,2);
SELECT email, last_name, first_name 
	FROM mycustomer 
	WHERE id IN (1,2)
ORDER BY last_name ASC;



SELECT * FROM mycustomer WHERE first_name = 'Jeff';
SELECT * FROM mycustomer WHERE first_name = 'jeff';
SELECT * FROM mycustomer WHERE first_name LIKE 'Je%';
SELECT * FROM mycustomer WHERE first_name LIKE 'je%';
SELECT * FROM mycustomer WHERE first_name ILIKE 'je%';
SELECT * FROM mycustomer WHERE first_name LIKE '_e%';


SELECT last_name, first_name FROM mycustomer WHERE since = '2023-09-07';
SELECT last_name, first_name FROM mycustomer WHERE since > '2023-09-07';
SELECT last_name, first_name FROM mycustomer WHERE since >= '2023-09-07';
SELECT last_name, first_name, since 
	FROM mycustomer 
	WHERE since >= '2023-09-07'
	ORDER BY since DESC;

/* Calculation in SELECT */

SELECT last_name || ', ' || first_name AS customer 
FROM mycustomer;

SELECT 
	FORMAT ('%s %s has been a valued customer since %s', 
			first_name, last_name, since)
	FROM mycustomer;

SELECT FORMAT ('%s. %s has been a valued customer since %s', 
			SUBSTRING (first_name, 1,1), last_name, since)
	FROM mycustomer;

SELECT TO_CHAR (NOW(), 'DAY');
SELECT TO_CHAR (NOW(), 'MON');
SELECT TO_CHAR (CURRENT_DATE, 'Day Month, DD, YYYY');
SELECT TO_CHAR (12345.55, '99G999G999D99L');


SELECT 15 * 4;	
SELECT 15 / 4;
SELECT 15 / 4.0;
SELECT MOD (15, 4);

SELECT PI();
SELECT PI()::INTEGER;
SELECT PI()::NUMERIC;

SELECT ROUND(PI()::NUMERIC);
SELECT ROUND(PI()::NUMERIC, 2);


SELECT last_name, since, EXTRACT (DAY FROM since) FROM mycustomer;
SELECT last_name, since, EXTRACT (YEAR FROM since) FROM mycustomer;
SELECT last_name, since, EXTRACT (DOW FROM since) FROM mycustomer;

SELECT last_name, since,  NOW()::date - since FROM mycustomer;
SELECT last_name, since, AGE( NOW(), since) FROM mycustomer;
SELECT last_name, since, EXTRACT (YEAR FROM AGE(NOW(), since)) AS nbr_years FROM mycustomer;

SELECT 'It is the ' || EXTRACT (DOY FROM current_date) || 'th day of the year';

SELECT 'It is the ' || EXTRACT (DOY FROM current_date) || 'th day of the year' as day_of_year;

SELECT FORMAT (
		'%s. %s is our oldest customer. ' 
		'He has been a valued customer for %s years, since %s', 
		SUBSTRING (first_name, 1,1), 
		last_name, 
		EXTRACT (YEAR FROM AGE( since, NOW())),
		since)
	FROM mycustomer
	ORDER BY since ASC
	LIMIT 1;

/* casting example */

SELECT NOW();

SELECT NOW()::DATE;


/*

Section: Primary Keys, Constraints and Relationships

*/

-- create the myproduct table

CREATE TABLE myproduct (
	product_nbr VARCHAR(10),
	name TEXT,
	price numeric
);	

-- add a primary key and a unique constraint
DROP TABLE IF EXISTS myproduct;

CREATE TABLE myproduct (
	nbr VARCHAR(10) PRIMARY KEY,
	name TEXT UNIQUE NOT NULL,
	price NUMERIC NOT NULL CHECK (price > 0) 
);

INSERT INTO myproduct (nbr, name, price) 
	VALUES 
		('ham_001','Hammer 200gr', 19.95),
		('ham_002', 'Hammer 1kg', 25.00),
		('chisel_004', 'Chisel stone', 39.95),
		('pli_019', 'Pliers red, adjustable', '13.50');

SELECT * FROM myproduct ORDER BY price ASC;

-- add table myorder to illustrate relations and foreign keys

DROP TABLE IF EXISTS myorder;

CREATE TABLE myorder (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	date DATE,
	product_nbr VARCHAR(10),
	qty INTEGER NOT NULL CHECK (qty > 0)
);

INSERT INTO myorder 
(date,product_nbr, qty) 
VALUES ('2.2.2025', 'chisel_004', 9);



-- nonsense order
INSERT INTO myorder 
(date,product_nbr, qty) 
VALUES ('2.2.2025', 'cheese_10', 9);


SELECT * FROM myorder;


SELECT * FROM myorder, myproduct
	WHERE myorder.product_id = myproduct.id;

-- add a foreign key constraint to make sure all orders refer to existing products and existing customers

DROP TABLE IF EXISTS myorder;

CREATE TABLE myorder (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	date DATE,
	customer_id INTEGER NOT NULL REFERENCES mycustomer (id),
	product_nbr VARCHAR(10) NOT NULL REFERENCES myproduct (nbr),
	qty INTEGER NOT NULL CHECK (qty > 0)
);

-- order for a chisel
INSERT INTO myorder (date,customer_id, product_nbr, qty) 
	VALUES ('2.2.2025', 1, 'chisel_004', 9);

-- nonsense order
INSERT INTO myorder 
(date,product_nbr, qty) 
VALUES ('2.2.2025', 'cheese_10', 9);

INSERT INTO myorder (date, customer_id, product_nbr, qty)
	VALUES 
		(NOW()::DATE, 1, 'ham_001', 1),
		(NOW()::DATE, 1, 'ham_002', 1),
		(NOW()::DATE-1, 2, 'chisel_004', 2),
		('2025-03-01', 2, 'pli_019', 4);

-- excercise slide 64

INSERT INTO mycustomer (id, email, first_name, last_name, since) 
	VALUES 
		(4,'marc@marclinster.com', 'Marc', 'Linster','2025-01-01'),
		(5,'jmu@gmail.lu','Jeff', 'Mueller','2025-02-01'),
		(6,'bini@hotmail.lu', 'Jean','Bintner','2025-03-01');

INSERT INTO myproduct (nbr, name, price)
   VALUES
       ('ham_003','Hammer Large 500gr', 19.95),
       ('ham_004', 'Hammer Extra Large 1000gr', 25.00),
       ('chisel_005', 'Chisel wood', 12.87),
       ('pli_020', 'Pliers black, fixed', 3.50);	


SELECT * FROM myorder o,
		myproduct p,
		mycustomer c
	WHERE 
		o.product_nbr = p.nbr
	AND 
o.customer_id = c.id;



SELECT o.id AS order_id, 
		o.date AS order_date, 
		c.first_name || ' ' || c.last_name AS customer_name,
		p.name AS product_name,
		p.price AS unit_price,
		o.qty AS order_qty,
		o.qty * p.price AS extended_price
	FROM myorder o,
		myproduct p, mycustomer c 
	WHERE o.product_nbr = p.nbr
		AND o.customer_id = c.id
	ORDER BY order_date ASC;


/* The NULL problem */

CREATE TABLE mytest (
	id INTEGER PRIMARY KEY,
	value1 INTEGER,
	value2 TEXT
);

TRUNCATE TABLE mytest;

INSERT INTO mytest (id, value1, value2) VALUES (1, 10, '20');
INSERT INTO mytest (id, value1, value2) VALUES (2, NULL, '20');
INSERT INTO mytest (id, value1, value2) VALUES (3, 0, NULL);
INSERT INTO mytest (id, value1, value2) VALUES (4, 10, '');
INSERT INTO mytest (id, value1) VALUES (5, NULL);


SELECT * FROM mytest;
SELECT * FROM mytest WHERE value1 < 15;
SELECT * FROM mytest WHERE value2 < '30';
SELECT * FROM mytest WHERE value2 IS NULL;
SELECT * FROM mytest WHERE value2 IS NOT NULL;
SELECT * FROM mytest WHERE value2 = '';

SELECT id, value1, value2 FROM mytest;

SELECT id, COALESCE(value1, -1) as value1, COALESCE(value2, 'this is NULL') as value2 FROM mytest;



/* Casts */

SELECT '100'::INTEGER; 
SELECT '100x'::INTEGER;
SELECT NOW()::DATE;
SELECT '2026-11-30'::DATE;
SELECT '2026-11-31'::DATE;
SELECT CAST('true' AS BOOLEAN),
	CAST('false' as BOOLEAN),
	CAST('T' as BOOLEAN),
	CAST('F' as BOOLEAN);

SELECT 
    format_type(c.castsource, NULL) AS source_type,
    format_type(c.casttarget, NULL) AS target_type
FROM pg_cast c
JOIN pg_type s ON c.castsource = s.oid
JOIN pg_type t ON c.casttarget = t.oid
ORDER BY 1, 2;


	
/*

Section: Database Joins

*/


SELECT * FROM myorder
	JOIN mycustomer
	ON myorder.customer_id = mycustomer.id;

SELECT 
	o.id AS order_id, 
	o.date AS order_date, 
	o.qty AS order_quantity, 
	c.first_name || ' ' || c.last_name AS customer_name
FROM myorder o
	JOIN mycustomer c
	ON o.customer_id = c.id;

-- customers even if they didn't order anything
SELECT * FROM mycustomer c
	LEFT OUTER JOIN myorder o
	ON c.id = o.customer_id;



SELECT 
	c.id, c.first_name, c.last_name, 
	o.date, o.qty, 
	p.name, p.price FROM mycustomer c
JOIN myorder o ON c.id = o.customer_id
JOIN myproduct p ON o.product_nbr = p.nbr;


-- customers with order details, or blank if they didn't order anything
SELECT * FROM mycustomer c
	LEFT JOIN myorder o ON c.id = o.customer_id
	LEFT JOIN myproduct p ON o.product_nbr = p.nbr;	
	
-- products that were never ordered

SELECT DISTINCT(p.*) FROM myproduct p
	LEFT JOIN myorder o ON o.product_nbr = p. nbr
	WHERE o.id IS NULL

-- customers who never ordered anything
SELECT * FROM mycustomer c
	LEFT OUTER JOIN myorder o
	ON c.id = o.customer_id
	WHERE o.id IS NULL;

/*

-- Section: Views

*/


CREATE OR REPLACE VIEW mycustomer_with_purchase_view AS 
	SELECT 
		c.id AS customer_id,
		FORMAT ('%s %s', c.first_name, c.last_name) AS customer_name,
		c.since AS customer_since,
		o.id AS order_number,
		o.date AS order_date,
		p.name AS product_name,
		p.price AS product_unit_price,
		p.price * o.qty AS extended_price
	FROM mycustomer c
		LEFT JOIN myorder o ON c.id = o.customer_id
		LEFT JOIN myproduct p ON o.product_nbr = p.nbr;	

SELECT * FROM mycustomer_with_purchase_view;

/****************************************************************************************************
                                              End of File
****************************************************************************************************/